### ISSUE TITLE
Version 1.0 veröffentlichen

### ISSUE THREAD

**Issue by tobi1196** [tobi1196/Infogruppe-RE---2#13]

**Comment by tobi1196** [comment]
Version 1.0 ist veröffentlicht.

**Comment by nipafx** [comment]
Das Release wurde nicht korrekt gemacht, es fehlt die JAR mit dem ausführbaren Programm.

**Comment by tobi1196** [comment]
Werde ich gleich noch verbessern.

**Comment by tobi1196** [comment]
JAR hinzugefügt.
