### ISSUE TITLE
Travis integrieren

### ISSUE THREAD

**Issue by tobi1196** [tobi1196/Infogruppe-RE---2#7]
@nicolaiparlog 

Können Sie Travis hinzufügen.

**Comment by nipafx** [comment]
Das Maven Setup ist fehlerhaft, d.h. `mvn clean install` funktioniert nicht. Ich würde das am entsprechenden Issue anmerken, aber es gibt keins...

**Comment by tobi1196** [comment]
@nicolaiparlog 

Jetzt sollte es funktionieren.

**Comment by nipafx** [comment]
Da dieses dir gehört, kann ich Travis nicht aktivieren. Dazu musst du Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen.

**Comment by tobi1196** [comment]
Habe es erledigt.
